//
//  Strings.swift — Table de traduction (clé → { fr, en })
//  Convention de clés : "section.element" (ex. "dashboard.cpu.title").
//

import Foundation

enum Strings {
    static let table: [String: [Lang: String]] = [

        // MARK: Onglets
        "tab.dashboard":   [.fr: "Tableau de bord", .en: "Dashboard"],
        "tab.features":    [.fr: "Fonctionnalités", .en: "Features"],
        "tab.cleaning":    [.fr: "Nettoyage", .en: "Cleanup"],
        "tab.uninstall":   [.fr: "Désinstaller", .en: "Uninstall"],
        "tab.maintenance": [.fr: "Maintenance", .en: "Maintenance"],
        "tab.log":         [.fr: "Journal", .en: "Log"],
        "tab.gains":       [.fr: "Gains", .en: "Savings"],
        "tab.settings":    [.fr: "Réglages", .en: "Settings"],
        "tab.guide":       [.fr: "Guide", .en: "Guide"],

        // MARK: Communs
        "common.refresh":     [.fr: "Actualiser", .en: "Refresh"],
        "common.close":       [.fr: "Fermer", .en: "Close"],
        "common.restoreAll":  [.fr: "Tout restaurer", .en: "Restore all"],
        "common.run":         [.fr: "Exécuter", .en: "Run"],
        "common.cancel":      [.fr: "Annuler", .en: "Cancel"],
        "common.continue":    [.fr: "Continuer", .en: "Continue"],
        "common.done":        [.fr: "Fait", .en: "Done"],
        "common.search":      [.fr: "Rechercher…", .en: "Search…"],
        "common.admin":       [.fr: "admin", .en: "admin"],
        "common.disabled":    [.fr: "DÉSACTIVÉ", .en: "DISABLED"],
        "common.revoke":      [.fr: "Révoquer", .en: "Revoke"],
        "common.open":        [.fr: "Ouvrir…", .en: "Open…"],
        "common.grant":       [.fr: "Accorder…", .en: "Grant…"],
        "common.finder":      [.fr: "Afficher dans le Finder", .en: "Show in Finder"],

        // MARK: Dashboard
        "dash.cpu":          [.fr: "Processeur", .en: "Processor"],
        "dash.cpu.load":     [.fr: "charge", .en: "load"],
        "dash.cpu.cores":    [.fr: "cœurs", .en: "cores"],
        "dash.mem":          [.fr: "Mémoire", .en: "Memory"],
        "dash.mem.wired":    [.fr: "Câblée", .en: "Wired"],
        "dash.mem.comp":     [.fr: "Compressée", .en: "Compressed"],
        "dash.mem.apps":     [.fr: "Apps", .en: "Apps"],
        "dash.mem.on":       [.fr: "sur", .en: "of"],
        "dash.disk":         [.fr: "Disque", .en: "Disk"],
        "dash.disk.free":    [.fr: "libres", .en: "free"],
        "dash.disk.read":    [.fr: "Lecture", .en: "Read"],
        "dash.disk.write":   [.fr: "Écriture", .en: "Write"],
        "dash.net":          [.fr: "Réseau", .en: "Network"],
        "dash.net.down":     [.fr: "Téléchargement", .en: "Download"],
        "dash.net.up":       [.fr: "Envoi", .en: "Upload"],
        "dash.net.live":     [.fr: "Débit instantané", .en: "Live throughput"],
        "net.test":          [.fr: "Tester le débit", .en: "Speed test"],
        "net.testing":       [.fr: "Mesure en cours…", .en: "Measuring…"],
        "net.result":        [.fr: "%@ Mbit/s en réception", .en: "%@ Mbit/s down"],

        // MARK: Ventilateur
        "fan.title":         [.fr: "Ventilation", .en: "Cooling"],
        "fan.modeManual":    [.fr: "Mode manuel", .en: "Manual mode"],
        "fan.modeAuto":      [.fr: "Mode automatique", .en: "Automatic mode"],
        "fan.rpm":           [.fr: "tr/min", .en: "rpm"],
        "fan.silent":        [.fr: "silencieux", .en: "silent"],
        "fan.max":           [.fr: "maximum", .en: "maximum"],
        "fan.manualToggle":  [.fr: "Contrôle manuel de la vitesse", .en: "Manual speed control"],
        "fan.target":        [.fr: "Vitesse cible", .en: "Target speed"],
        "fan.apply":         [.fr: "Valider", .en: "Apply"],
        "fan.preset.silent": [.fr: "Silencieux", .en: "Silent"],
        "fan.preset.medium": [.fr: "Moyen", .en: "Medium"],
        "fan.preset.max":    [.fr: "Maximum", .en: "Maximum"],
        "fan.startup":       [.fr: "Réappliquer cette vitesse au démarrage", .en: "Reapply this speed at startup"],
        "fan.safe.manual":   [.fr: "Vitesse limitée au min/max du Mac. Aucun risque de surchauffe.",
                              .en: "Speed capped to the Mac's min/max. No overheating risk."],
        "fan.safe.auto":     [.fr: "Un seul mot de passe à la première activation, puis plus rien.",
                              .en: "One password on first use, then never again."],
        "fan.blocked":       [.fr: "Contrôle indisponible", .en: "Control unavailable"],
        "fan.blocked.desc":  [.fr: "La lecture des capteurs fonctionne, mais l'écriture du ventilateur est réservée à Apple Silicon sous macOS 26–27.",
                              .en: "Sensor reading works, but fan writing is limited to Apple Silicon on macOS 26–27."],

        // MARK: Fonctionnalités
        "feat.footer":       [.fr: "%d/%d désactivés. Tout est réversible, aucun fichier supprimé.",
                              .en: "%d/%d disabled. Fully reversible, no files removed."],
        "feat.reboot":       [.fr: "Redémarrage requis pour l'effet complet. macOS (SIP) garde les agents Apple actifs jusqu'au redémarrage, et peut même en réactiver certains au démarrage : MacTuner les ré-applique alors automatiquement à chaque ouverture de session.",
                              .en: "Restart needed for full effect. macOS (SIP) keeps Apple agents alive until reboot, and may even re-enable some at startup: MacTuner then reapplies them automatically at every login."],
        "feat.drift":        [.fr: "%d désactivation(s) ont été réactivées par macOS (généralement au redémarrage).",
                              .en: "%d disabled item(s) were re-enabled by macOS (usually at reboot)."],
        "feat.reapply":      [.fr: "Réappliquer", .en: "Reapply"],
        "feat.details":      [.fr: "Détails", .en: "Details"],
        "feat.restart":      [.fr: "Redémarrer…", .en: "Restart…"],
        "feat.search":       [.fr: "Rechercher une fonctionnalité, une app…", .en: "Search a feature or app…"],
        "feat.subprocesses": [.fr: "Sous-processus (désactivables un par un)", .en: "Sub-processes (toggle individually)"],
        "feat.usage":        [.fr: "%d processus · %@ RAM · CPU %@", .en: "%d processes · %@ RAM · CPU %@"],
        "feat.what":         [.fr: "Ce que ça fait", .en: "What it does"],
        "feat.affects":      [.fr: "Apps et fonctions concernées", .en: "Affected apps and features"],
        "feat.breaks":       [.fr: "Si vous désactivez", .en: "If you disable it"],
        "feat.reenable":     [.fr: "À la réactivation", .en: "When re-enabled"],
        "feat.confirm":      [.fr: "Désactiver « %@ » ?", .en: "Disable “%@”?"],
        "feat.confirm.ok":   [.fr: "Désactiver", .en: "Disable"],
        "feat.confirm.reboot": [.fr: "macOS (SIP) peut garder le service actif jusqu'au prochain redémarrage.",
                              .en: "macOS (SIP) may keep the service active until the next restart."],
        "feat.sip.on":       [.fr: "SIP est activé. Les réglages « Effet immédiat » ci-dessous s'appliquent tout de suite. Ceux qui reposent sur des agents Apple (Siri, Apple Intelligence, télémétrie) ne peuvent pas être arrêtés tant que SIP est actif : leurs processus continuent de tourner. Pour les couper réellement, désactivez SIP depuis la Recovery.",
                              .en: "SIP is enabled. The “Immediate effect” settings below apply right away. Those relying on Apple agents (Siri, Apple Intelligence, telemetry) can't be stopped while SIP is on: their processes keep running. To truly turn them off, disable SIP from Recovery."],
        "feat.sip.off":      [.fr: "SIP est désactivé. Toutes les fonctionnalités sont pleinement effectives, y compris l'arrêt des agents Apple.",
                              .en: "SIP is disabled. Every feature is fully effective, including stopping Apple agents."],
        "feat.count":        [.fr: "%d réglages", .en: "%d settings"],
        "feat.sip.chip":     [.fr: "SIP requis", .en: "SIP required"],
        "feat.sip.blocked":  [.fr: "Non modifiable tant que SIP est activé : ce réglage arrête un agent Apple, ce que macOS refuse sous SIP. Désactivez SIP depuis la Recovery pour l'utiliser.",
                              .en: "Not changeable while SIP is on: this setting stops an Apple agent, which macOS refuses under SIP. Disable SIP from Recovery to use it."],
        "feat.sip.compatible.title": [.fr: "Effet immédiat", .en: "Immediate effect"],
        "feat.sip.compatible.desc": [.fr: "Réglages de préférences et commandes système. S'appliquent tout de suite, que SIP soit activé ou non.",
                              .en: "Preference settings and system commands. They apply right away, whether SIP is on or off."],
        "feat.sip.required.title": [.fr: "Nécessite SIP désactivé", .en: "Requires SIP disabled"],
        "feat.sip.required.desc.on": [.fr: "Ces réglages arrêtent des agents Apple. Avec SIP activé, macOS refuse de les stopper et les relance au démarrage : ils ne deviendront effectifs qu'après avoir désactivé SIP.",
                              .en: "These settings stop Apple agents. With SIP on, macOS refuses to stop them and relaunches them at boot: they only take effect after you disable SIP."],
        "feat.sip.required.desc.off": [.fr: "Ces agents Apple sont réellement arrêtés, puis ré-appliqués à chaque ouverture de session.",
                              .en: "These Apple agents are truly stopped, then reapplied at every login."],

        // MARK: Maintenance
        "maint.title":       [.fr: "Maintenance & optimisation", .en: "Maintenance & optimization"],
        "maint.subtitle":    [.fr: "Actions ponctuelles pour rafraîchir le système. Sûres, sans perte de données.",
                              .en: "One-off actions to refresh the system. Safe, no data loss."],
        "maint.dns.name":    [.fr: "Vider le cache DNS", .en: "Flush DNS cache"],
        "maint.dns.what":    [.fr: "Purge la résolution de noms et relance mDNSResponder.",
                              .en: "Clears name resolution and restarts mDNSResponder."],
        "maint.purge.name":  [.fr: "Libérer la mémoire inactive", .en: "Free inactive memory"],
        "maint.purge.what":  [.fr: "Vide les pages mémoire inactives et les caches disque.",
                              .en: "Flushes inactive memory pages and disk caches."],
        "maint.spot.name":   [.fr: "Réindexer Spotlight", .en: "Reindex Spotlight"],
        "maint.spot.what":   [.fr: "Reconstruit l'index de recherche du disque de démarrage.",
                              .en: "Rebuilds the startup disk's search index."],
        "maint.tm.name":     [.fr: "Purger les snapshots Time Machine locaux", .en: "Purge local Time Machine snapshots"],
        "maint.tm.what":     [.fr: "Supprime les instantanés locaux, recréés automatiquement.",
                              .en: "Removes local snapshots, recreated automatically."],
        "maint.icon.name":   [.fr: "Purger le cache des icônes", .en: "Rebuild icon cache"],
        "maint.icon.what":   [.fr: "Corrige les icônes blanches ou manquantes puis relance le Dock.",
                              .en: "Fixes blank or missing icons then restarts the Dock."],
        "maint.ls.name":     [.fr: "Reconstruire Launch Services", .en: "Rebuild Launch Services"],
        "maint.ls.what":     [.fr: "Nettoie le menu « Ouvrir avec » et les associations de fichiers.",
                              .en: "Cleans the “Open with” menu and file associations."],
        "maint.dock.name":   [.fr: "Redémarrer Dock, Finder & barre des menus", .en: "Restart Dock, Finder & menu bar"],
        "maint.dock.what":   [.fr: "Relance l'interface pour corriger un blocage.",
                              .en: "Restarts the UI to fix a freeze."],

        // MARK: Nettoyage
        "clean.title":       [.fr: "Nettoyage", .en: "Cleanup"],
        "clean.detected":    [.fr: "Espace récupérable détecté : %@", .en: "Reclaimable space found: %@"],
        "clean.scanPrompt":  [.fr: "Lancez une analyse pour mesurer l'espace récupérable.", .en: "Run an analysis to measure reclaimable space."],
        "clean.freed":       [.fr: "%@ libérés", .en: "%@ freed"],
        "clean.progress.title": [.fr: "Nettoyage en cours…", .en: "Cleaning…"],
        "clean.progress.done":  [.fr: "Nettoyage terminé", .en: "Cleanup complete"],
        "clean.progress.freed": [.fr: "%@ libérés", .en: "%@ freed"],

        // MARK: Journal
        "gains.title":       [.fr: "Vos gains", .en: "Your savings"],
        "gains.subtitle":    [.fr: "Le bilan mesuré de ce que MacTuner vous fait économiser. Rien d'estimé, tout est relevé sur ce Mac.",
                              .en: "The measured tally of what MacTuner saves you. Nothing estimated, everything read from this Mac."],
        "log.title":         [.fr: "Journal des suppressions", .en: "Deletion log"],
        "log.subtitle":      [.fr: "Tout ce que MacTuner a réellement supprimé (nettoyage et désinstallations).",
                              .en: "Everything MacTuner actually deleted (cleanup and uninstalls)."],
        "log.count":         [.fr: "%d suppressions · %@ au total", .en: "%d deletions · %@ total"],
        "log.empty":         [.fr: "Aucune suppression enregistrée pour l'instant. Lancez un nettoyage ou une désinstallation : chaque fichier supprimé apparaîtra ici.",
                              .en: "No deletions recorded yet. Run a cleanup or an uninstall: every deleted file will show up here."],
        "log.noMatch":       [.fr: "Aucune entrée ne correspond au filtre.", .en: "No entry matches the filter."],
        "log.search":        [.fr: "Filtrer par nom, chemin ou origine…", .en: "Filter by name, path or origin…"],
        "log.clear":         [.fr: "Vider le journal", .en: "Clear log"],
        "log.clear.confirm": [.fr: "Vider le journal des suppressions ?", .en: "Clear the deletion log?"],
        "log.clear.msg":     [.fr: "Seul l'historique affiché est effacé, aucun fichier n'est touché.",
                              .en: "Only the displayed history is erased, no files are affected."],
        "clean.scan":        [.fr: "Analyser", .en: "Analyze"],
        "clean.rescan":      [.fr: "Réanalyser", .en: "Re-analyze"],
        "clean.safeNote":    [.fr: "Seul le contenu des dossiers listés est supprimé, jamais les dossiers eux-mêmes ni quoi que ce soit hors de votre dossier personnel.",
                              .en: "Only the contents of the listed folders are removed, never the folders themselves nor anything outside your home folder."],
        "clean.cleanBtn":    [.fr: "Nettoyer la sélection", .en: "Clean selection"],
        "clean.cleanBtnSize": [.fr: "Nettoyer la sélection (%@)", .en: "Clean selection (%@)"],
        "clean.confirm":     [.fr: "Confirmer le nettoyage ?", .en: "Confirm cleanup?"],
        "clean.confirm.ok":  [.fr: "Supprimer définitivement", .en: "Delete permanently"],
        "clean.confirm.msg": [.fr: "Catégories : %@.\n\nEnviron %@ seront supprimés définitivement. Cette action est irréversible.",
                              .en: "Categories: %@.\n\nAbout %@ will be permanently deleted. This action is irreversible."],

        // MARK: Désinstaller
        "uninst.title":      [.fr: "Désinstaller", .en: "Uninstall"],
        "uninst.apps":       [.fr: "Apps", .en: "Apps"],
        "uninst.cli":        [.fr: "CLI", .en: "CLI"],
        "uninst.hidden":     [.fr: "Cachés", .en: "Hidden"],
        "uninst.selectApp":  [.fr: "Sélectionnez une application", .en: "Select an application"],
        "uninst.selectHint": [.fr: "MacTuner trouvera toutes ses traces (préférences, caches, conteneurs, agents, démons, ouverture à la connexion) pour une suppression sans résidu.",
                              .en: "MacTuner will find all its traces (preferences, caches, containers, agents, daemons, login items) for a residue-free removal."],
        "uninst.done":       [.fr: "« %@ » désinstallée : %d élément(s), %@ libérés", .en: "“%@” uninstalled: %d item(s), %@ freed"],
        "uninst.cliTool":    [.fr: "Outil en ligne de commande", .en: "Command-line tool"],
        "uninst.aliases":    [.fr: "alias : %@", .en: "aliases: %@"],
        "uninst.hiddenItem": [.fr: "Élément masqué (%@)", .en: "Hidden item (%@)"],
        "uninst.detected":   [.fr: "%d élément(s) détecté(s)", .en: "%d item(s) found"],
        "uninst.all":        [.fr: "Tout", .en: "All"],
        "uninst.highConf":   [.fr: "Confiance élevée", .en: "High confidence"],
        "uninst.none":       [.fr: "Rien", .en: "None"],
        "uninst.noResidue":  [.fr: "Aucun résidu trouvé.", .en: "No residue found."],
        "uninst.byName":     [.fr: "par nom", .en: "by name"],
        "uninst.byNameHelp": [.fr: "Correspondance par nom d'app, vérifiez avant de supprimer.", .en: "Matched by app name, verify before removing."],
        "uninst.footer":     [.fr: "Les cases « par nom » sont des correspondances probables, vérifiez-les. Personnels → Corbeille, système → suppression admin.",
                              .en: "“By name” items are likely matches, check them. Personal → Trash, system → admin removal."],
        "uninst.btn":        [.fr: "Désinstaller (%@)", .en: "Uninstall (%@)"],
        "uninst.confirm":    [.fr: "Désinstaller « %@ » ?", .en: "Uninstall “%@”?"],
        "uninst.confirm.ok": [.fr: "Tout supprimer", .en: "Remove everything"],
        "uninst.confirm.msg": [.fr: "%d élément(s), environ %@.\n\nLes fichiers personnels vont à la Corbeille (récupérables). Les éléments « admin » sont supprimés définitivement après mot de passe. Videz la Corbeille ensuite pour ne laisser aucune trace.",
                              .en: "%d item(s), about %@.\n\nPersonal files go to the Trash (recoverable). “Admin” items are permanently deleted after a password. Empty the Trash afterwards to leave no trace."],

        // MARK: Résidus (types)
        "res.appBundle":     [.fr: "Application", .en: "Application"],
        "res.preferences":   [.fr: "Préférences", .en: "Preferences"],
        "res.appSupport":    [.fr: "Support d'application", .en: "Application support"],
        "res.caches":        [.fr: "Caches", .en: "Caches"],
        "res.container":     [.fr: "Conteneur (sandbox)", .en: "Container (sandbox)"],
        "res.groupContainer": [.fr: "Conteneur de groupe", .en: "Group container"],
        "res.savedState":    [.fr: "État de fenêtres", .en: "Window state"],
        "res.logs":          [.fr: "Journaux", .en: "Logs"],
        "res.httpStorage":   [.fr: "Stockage HTTP / cookies", .en: "HTTP storage / cookies"],
        "res.webkit":        [.fr: "Données WebKit", .en: "WebKit data"],
        "res.scripts":       [.fr: "Scripts d'application", .en: "Application scripts"],
        "res.launchAgent":   [.fr: "Agent de lancement", .en: "Launch agent"],
        "res.launchDaemon":  [.fr: "Démon de lancement (système)", .en: "Launch daemon (system)"],
        "res.helper":        [.fr: "Outil d'assistance privilégié", .en: "Privileged helper"],
        "res.loginItem":     [.fr: "Ouverture à la connexion", .en: "Login item"],
        "res.executable":    [.fr: "Exécutable / lien", .en: "Executable / link"],
        "res.config":        [.fr: "Configuration", .en: "Configuration"],
        "res.data":          [.fr: "Données du programme", .en: "Program data"],

        // MARK: Gains
        "gains.yours":       [.fr: "Vos gains", .en: "Your savings"],
        "gains.ramFreed":    [.fr: "RAM qui sera libérée au redémarrage (mesurée sur chaque service désactivé)",
                              .en: "RAM that will be freed after restart (measured on each disabled service)"],
        "gains.procs":       [.fr: "Processus qui ne se relanceront plus après redémarrage",
                              .en: "Processes that won't relaunch after restart"],
        "gains.diskFreed":   [.fr: "Espace disque libéré au total via l'onglet Nettoyage", .en: "Total disk space freed via the Cleanup tab"],
        "gains.appsFreed":   [.fr: "Espace libéré par les applications désinstallées", .en: "Space freed by uninstalled apps"],
        "gains.potential":   [.fr: "Potentiel restant", .en: "Remaining potential"],
        "gains.liveRAM":     [.fr: "RAM utilisée en ce moment par %d processus des fonctions encore actives",
                              .en: "RAM used right now by %d processes of still-active features"],
        "gains.liveCPU":     [.fr: "Temps CPU cumulé consommé par ces services depuis le démarrage du Mac",
                              .en: "Cumulative CPU time used by these services since the Mac started"],
        "gains.reclaimable": [.fr: "Espace disque récupérable maintenant (dernière analyse)", .en: "Disk space reclaimable now (last scan)"],
        "gains.reclaimHint": [.fr: "Espace récupérable : lancez une analyse dans l'onglet Nettoyage", .en: "Reclaimable space: run an analysis in the Cleanup tab"],
        "gains.activeServices": [.fr: "Services actifs, triés par mémoire", .en: "Active services, sorted by memory"],
        "gains.measuring":   [.fr: "Mesure en cours…", .en: "Measuring…"],
        "gains.noData":      [.fr: "Aucune mesure. Cliquez sur Actualiser.", .en: "No data yet. Click Refresh."],
        "gains.note":        [.fr: "La RAM « libérée » est celle qu'occupaient les services au moment de leur désactivation. macOS recycle aussitôt cette mémoire, donc les compteurs globaux peuvent sembler inchangés : le vrai gain est moins de processus, de réveils et d'E/S.",
                              .en: "“Freed” RAM is what the services used when disabled. macOS recycles that memory right away, so global counters may look unchanged: the real gain is fewer processes, wake-ups and I/O."],
        "gains.refresh":     [.fr: "Actualiser les mesures", .en: "Refresh measurements"],
        "gains.procShort":   [.fr: "%d proc · %@ · CPU %@", .en: "%d proc · %@ · CPU %@"],

        // MARK: Réglages
        "set.tagline":       [.fr: "Centre de contrôle, réglages et entretien pour Mac Apple Silicon.",
                              .en: "Control center, tuning and maintenance for Apple Silicon Macs."],
        "set.language":      [.fr: "Langue", .en: "Language"],
        "set.language.desc": [.fr: "Choisissez la langue de l'interface.", .en: "Choose the interface language."],
        "set.compat":        [.fr: "Compatibilité", .en: "Compatibility"],
        "set.compat.arch":   [.fr: "Architecture", .en: "Architecture"],
        "set.compat.os":     [.fr: "Système", .en: "System"],
        "set.compat.fan":    [.fr: "Contrôle du ventilateur", .en: "Fan control"],
        "set.compat.supported": [.fr: "Pris en charge", .en: "Supported"],
        "set.compat.unvalidated": [.fr: "Non validé", .en: "Not validated"],
        "set.compat.active": [.fr: "Actif", .en: "Active"],
        "set.compat.blocked": [.fr: "Bloqué", .en: "Blocked"],
        "set.auth":          [.fr: "Autorisations", .en: "Permissions"],
        "set.auth.fda":      [.fr: "Accès complet au disque", .en: "Full Disk Access"],
        "set.auth.fda.on":   [.fr: "Accordé : nettoyage et désinstallation complets",
                              .en: "Granted: full cleanup and uninstall"],
        "set.auth.fda.off":  [.fr: "Recommandé pour Safari, Mail et les sauvegardes",
                              .en: "Recommended for Safari, Mail and backups"],
        "set.auth.admin":    [.fr: "Droits admin persistants", .en: "Persistent admin rights"],
        "set.auth.admin.on": [.fr: "Actifs pour Spotlight, Power Nap, son de démarrage",
                              .en: "Active for Spotlight, Power Nap, startup chime"],
        "set.auth.admin.off": [.fr: "Non installés", .en: "Not installed"],
        "set.auth.fan":      [.fr: "Autorisation ventilateur", .en: "Fan authorization"],
        "set.auth.fan.on":   [.fr: "Changement de vitesse sans mot de passe",
                              .en: "Speed changes without a password"],
        "set.auth.fan.off":  [.fr: "Proposée à la 1re activation du mode manuel",
                              .en: "Offered on first manual-mode use"],
        "set.data":          [.fr: "Données de l'application", .en: "Application data"],
        "set.reset":         [.fr: "Réinitialiser les compteurs et préférences", .en: "Reset counters and preferences"],
        "set.reset.desc":    [.fr: "Efface les statistiques et l'écran d'accueil. Ni réglages système, ni fichiers touchés.",
                              .en: "Clears stats and the welcome screen. No system settings or files affected."],
        "set.reset.btn":     [.fr: "Réinitialiser", .en: "Reset"],
        "set.about":         [.fr: "À propos", .en: "About"],
        "set.about.desc":    [.fr: "MacTuner n'agit que par des mécanismes réversibles d'Apple (launchctl, defaults, IOKit SMC). Aucun fichier système modifié, un garde-fou interdit toute suppression hors des zones sûres.",
                              .en: "MacTuner only uses reversible Apple mechanisms (launchctl, defaults, IOKit SMC). No system files modified, a guard blocks any deletion outside safe areas."],
        "set.hardware":      [.fr: "Matériel", .en: "Hardware"],
        "set.credits":       [.fr: "Créé par Rodolphe Vandaele · Libre et open source",
                              .en: "Created by Rodolphe Vandaele · Free and open source"],
        "set.website":       [.fr: "Site web", .en: "Website"],
        "set.source":        [.fr: "Code source", .en: "Source code"],

        // MARK: Suppression de MacTuner
        "set.remove":        [.fr: "Supprimer MacTuner", .en: "Remove MacTuner"],
        "set.remove.desc":   [.fr: "Supprime l'application et toutes ses données (préférences, autorisations, langue). Aucune trace ne subsiste.",
                              .en: "Removes the app and all its data (preferences, permissions, language). No trace remains."],
        "set.remove.btn":    [.fr: "Supprimer MacTuner…", .en: "Remove MacTuner…"],
        "set.remove.restore": [.fr: "Réactiver aussi les fonctionnalités que j'ai désactivées",
                              .en: "Also re-enable the features I disabled"],
        "set.remove.confirm": [.fr: "Supprimer MacTuner définitivement ?", .en: "Permanently remove MacTuner?"],
        "set.remove.msg":    [.fr: "L'app ira à la Corbeille avec toutes ses données. Les règles admin et le démon de ventilation seront retirés (mot de passe requis). MacTuner se fermera ensuite.",
                              .en: "The app will move to the Trash with all its data. Admin rules and the fan daemon will be removed (password required). MacTuner will then quit."],
        "set.remove.ok":     [.fr: "Tout supprimer", .en: "Remove everything"],

        // MARK: Guide
        "guide.title":       [.fr: "Guide de MacTuner", .en: "MacTuner guide"],
        "guide.intro":       [.fr: "Un principe partout : rien n'est fait dans votre dos, tout est mesuré et réversible, et un garde-fou empêche toute suppression de fichiers critiques.",
                              .en: "One principle throughout: nothing happens behind your back, everything is measured and reversible, and a guard blocks any deletion of critical files."],
        "guide.s1":          [.fr: "Surveiller", .en: "Monitor"],
        "guide.s1.sub":      [.fr: "Voir l'état du Mac en temps réel", .en: "See your Mac's status in real time"],
        "guide.s2":          [.fr: "Régler", .en: "Tune"],
        "guide.s2.sub":      [.fr: "Alléger et personnaliser le système", .en: "Lighten and customize the system"],
        "guide.s3":          [.fr: "Libérer de l'espace", .en: "Free up space"],
        "guide.s3.sub":      [.fr: "Nettoyer et désinstaller sans résidu", .en: "Clean and uninstall with no leftovers"],
        "guide.s4":          [.fr: "En toute sécurité", .en: "Safely"],
        "guide.s4.sub":      [.fr: "Ce qui protège votre Mac", .en: "What protects your Mac"],
        "guide.dash.t":      [.fr: "Tableau de bord", .en: "Dashboard"],
        "guide.dash.d":      [.fr: "Charge CPU par cœur, mémoire détaillée, disque, réseau, température et ventilation. Lus du système et du SMC, sans mot de passe, toutes les 1,5 s.",
                              .en: "Per-core CPU load, detailed memory, disk, network, temperature and cooling. Read from the system and SMC, no password, every 1.5 s."],
        "guide.fan.t":       [.fr: "Ventilation", .en: "Cooling"],
        "guide.fan.d":       [.fr: "Contrôle manuel de la vitesse borné au min/max constructeur, sans risque de surchauffe. Un mot de passe à la première activation, puis silencieux. Réapplication au démarrage possible.",
                              .en: "Manual speed control capped to the maker's min/max, no overheating risk. One password on first use, then silent. Optional reapply at startup."],
        "guide.gains.t":     [.fr: "Gains", .en: "Savings"],
        "guide.gains.d":     [.fr: "Mesures réelles : RAM occupée par chaque service, temps CPU cumulé, RAM et espace disque libérés.",
                              .en: "Real measurements: RAM used by each service, cumulative CPU time, RAM and disk space freed."],
        "guide.feat.t":      [.fr: "Fonctionnalités", .en: "Features"],
        "guide.feat.d":      [.fr: "34 fonctions désactivables : Siri, Apple Intelligence, télémétrie, iCloud, animations… Chaque fiche explique le rôle, ce qui casse et le coût de réactivation. Que des réglages réversibles.",
                              .en: "34 toggleable features: Siri, Apple Intelligence, telemetry, iCloud, animations… Each card explains the role, what breaks and the re-enable cost. Reversible settings only."],
        "guide.maint.t":     [.fr: "Maintenance", .en: "Maintenance"],
        "guide.maint.d":     [.fr: "Vider le cache DNS, libérer la mémoire, réindexer Spotlight, purger les snapshots Time Machine, purger le cache des icônes, reconstruire Launch Services.",
                              .en: "Flush DNS, free memory, reindex Spotlight, purge Time Machine snapshots, rebuild the icon cache, rebuild Launch Services."],
        "guide.clean.t":     [.fr: "Nettoyage", .en: "Cleanup"],
        "guide.clean.d":     [.fr: "18 catégories de fichiers régénérables : caches, journaux, builds Xcode, navigateurs, messageries, conteneurs orphelins. Vous cochez, vérifiez, confirmez.",
                              .en: "18 categories of regenerable files: caches, logs, Xcode builds, browsers, chat apps, orphaned containers. You tick, review, confirm."],
        "guide.uninst.t":    [.fr: "Désinstaller", .en: "Uninstall"],
        "guide.uninst.d":    [.fr: "Apps, outils CLI (alias regroupés, données résolues) et éléments cachés. Préférences, caches, conteneurs, agents, démons : aucune trace. Vos fichiers vont à la Corbeille.",
                              .en: "Apps, CLI tools (grouped aliases, resolved data) and hidden items. Preferences, caches, containers, agents, daemons: no leftovers. Files go to the Trash."],
        "guide.guard.t":     [.fr: "Garde-fous", .en: "Safeguards"],
        "guide.guard.d":     [.fr: "Liste blanche stricte : /System, /usr, apps Apple, Documents, trousseaux, iCloud, Mail, Messages, clés SSH refusés d'office. Droits admin limités via sudoers révocable.",
                              .en: "Strict allow-list: /System, /usr, Apple apps, Documents, keychains, iCloud, Mail, Messages, SSH keys denied by default. Admin rights limited via revocable sudoers."],
        "guide.compat.t":    [.fr: "Compatibilité", .en: "Compatibility"],
        "guide.compat.d":    [.fr: "Conçu pour Apple Silicon sous macOS 26 et 27. Les fonctions à risque hors périmètre sont bloquées automatiquement. Voir l'onglet Réglages pour l'état de votre Mac.",
                              .en: "Built for Apple Silicon on macOS 26 and 27. Risky out-of-scope features are auto-blocked. See the Settings tab for your Mac's status."],

        // MARK: Onboarding
        "onb.welcome":       [.fr: "Bienvenue dans MacTuner", .en: "Welcome to MacTuner"],
        "onb.lang.q":        [.fr: "Choisissez votre langue", .en: "Choose your language"],
        "onb.perm.intro":    [.fr: "Deux accès facultatifs débloquent toutes les fonctions.",
                              .en: "Two optional permissions unlock every feature."],
        "onb.fda.desc":      [.fr: "Nécessaire au nettoyage complet (Safari, Mail, sauvegardes iPhone). macOS interdit de le demander par popup : ouvrez les Réglages, ajoutez MacTuner, activez, puis relancez.",
                              .en: "Needed for full cleanup (Safari, Mail, iPhone backups). macOS forbids a popup request: open Settings, add MacTuner, enable it, then relaunch."],
        "onb.fda.open":      [.fr: "Ouvrir les Réglages…", .en: "Open Settings…"],
        "onb.fda.recheck":   [.fr: "Re-vérifier", .en: "Re-check"],
        "onb.fda.relaunch":  [.fr: "Relancer MacTuner", .en: "Relaunch MacTuner"],
        "onb.granted":       [.fr: "Accordé", .en: "Granted"],
        "onb.notGranted":    [.fr: "Non accordé", .en: "Not granted"],
        "onb.admin.desc":    [.fr: "Requis pour les réglages « Système » (Spotlight, Power Nap, son de démarrage). Vous pouvez vérifier vos droits dès maintenant.",
                              .en: "Required for the “System” settings (Spotlight, Power Nap, startup chime). You can check your rights now."],
        "onb.admin.verify":  [.fr: "Vérifier maintenant…", .en: "Verify now…"],
        "onb.admin.ok":      [.fr: "Vérifié", .en: "Verified"],
    ]
}
