//
//  TweakCatalog.swift — MacTuner
//
import SwiftUI
import AppKit
import IOKit
import IOKit.ps
import Darwin

// MARK: - Catalogue des fonctionnalités

let groupOrder: [TweakGroup] = TweakGroup.allCases

let allTweaks: [Tweak] = [

    // ── Assistant & suggestions ──────────────────────────────────────────
    Tweak(id: "siri", name: LStr("Siri & Assistant", "Siri & Assistant"), icon: "waveform.circle.fill",
        group: .assistant,
        what: LStr("L'assistant vocal complet : agent Siri, reconnaissance, synthèse vocale, inférence locale et base de connaissances. Ces 7 processus tournent en permanence même si vous n'utilisez jamais Siri. Le réglage maître « Siri » de Réglages Système est aussi coupé, sinon macOS relance les agents à chaque démarrage.",
                   "The full voice assistant: Siri agent, recognition, speech synthesis, on-device inference and knowledge base. These 7 processes run constantly even if you never use Siri. The master “Siri” switch in System Settings is also turned off, otherwise macOS relaunches the agents at every startup."),
        affects: [LStr("Siri", "Siri"), LStr("« Dis Siri »", "“Hey Siri”"), LStr("Dictée vocale", "Voice dictation"),
                  LStr("Raccourcis (actions Siri)", "Shortcuts (Siri actions)"), LStr("Réglages > Siri", "Settings > Siri"),
                  LStr("Contrôle vocal partiel", "Partial Voice Control")],
        breaks: LStr("Siri ne répond plus du tout : ni la touche dédiée, ni « Dis Siri », ni l'icône de la barre des menus. La dictée vocale (fn fn) devient indisponible dans toutes les apps. Les Raccourcis déclenchés à la voix échouent silencieusement. Le panneau Réglages > Siri peut afficher des erreurs. Les apps tierces qui intègrent SiriKit perdent cette intégration.",
                     "Siri stops responding entirely: no dedicated key, no “Hey Siri”, no menu-bar icon. Voice dictation (fn fn) becomes unavailable in every app. Voice-triggered Shortcuts fail silently. The Settings > Siri panel may show errors. Third-party apps that integrate SiriKit lose that integration."),
        reenable: LStr("Retour immédiat de Siri et de la dictée, sans perte de données. La première requête peut être lente le temps que les agents redémarrent (quelques secondes).",
                       "Siri and dictation return immediately with no data loss. The first request may be slow while the agents restart (a few seconds)."),
        risk: .moyen,
        mechanisms: [.agents(["com.apple.Siri.agent", "com.apple.assistantd", "com.apple.assistant_service",
                              "com.apple.siriactionsd", "com.apple.siriknowledged", "com.apple.sirittsd",
                              "com.apple.siriinferenced"]),
                     // Réglages maîtres consultés par macOS au démarrage : sans eux, les
                     // agents Siri sont ré-activés à chaque boot (self-healing).
                     .defaultsKey(domain: "com.apple.assistant.support", key: "Assistant Enabled",
                                  disabledValue: .bool(false), enabledValue: .bool(true), killall: nil),
                     .defaultsKey(domain: "com.apple.Siri", key: "VoiceTriggerUserEnabled",
                                  disabledValue: .bool(false), enabledValue: nil, killall: nil)]),

    Tweak(id: "appleintelligence", name: LStr("Apple Intelligence", "Apple Intelligence"), icon: "sparkles",
        group: .assistant,
        what: LStr("Les daemons d'IA générative de macOS 26/27 : plateforme d'intelligence, expériences génératives et construction de la base de connaissances locale. Ils consomment CPU, mémoire et plusieurs Go de disque. macOS n'offre aucun réglage maître public pour les couper : il peut donc les réactiver de lui-même, et MacTuner les re-coupe alors automatiquement (au login et dès que macOS y touche).",
                   "The generative-AI daemons of macOS 26/27: intelligence platform, generative experiences and local knowledge-base building. They use CPU, memory and several GB of disk. macOS offers no public master switch to turn them off: it may re-enable them on its own, and MacTuner then re-disables them automatically (at login and whenever macOS touches them)."),
        affects: [LStr("Outils d'écriture (toutes les apps)", "Writing Tools (all apps)"),
                  LStr("Résumés de notifications", "Notification summaries"), LStr("Genmoji", "Genmoji"),
                  LStr("Image Playground", "Image Playground"), LStr("Siri (capacités avancées)", "Siri (advanced abilities)"),
                  LStr("Mail (résumés, tri prioritaire)", "Mail (summaries, priority)"), LStr("Photos (gomme magique)", "Photos (Clean Up)")],
        breaks: LStr("Les Outils d'écriture disparaissent des menus contextuels. Les notifications ne sont plus résumées. Genmoji et Image Playground cessent de générer. Siri retombe sur ses capacités classiques. Dans Mail : plus de résumés ni de boîte prioritaire intelligente. La gomme magique de Photos peut échouer.",
                     "Writing Tools disappear from context menus. Notifications are no longer summarized. Genmoji and Image Playground stop generating. Siri falls back to its classic abilities. In Mail: no more summaries or smart priority inbox. Photos Clean Up may fail."),
        reenable: LStr("Les fonctions reviennent, mais les modèles peuvent devoir être retéléchargés (plusieurs Go) et la base de connaissances locale se reconstruit sur plusieurs jours.",
                       "The features return, but the models may need to be re-downloaded (several GB) and the local knowledge base rebuilds over several days."),
        risk: .moyen,
        mechanisms: [.agents(["com.apple.intelligenceplatformd", "com.apple.generativeexperiencesd",
                              "com.apple.knowledgeconstructiond"])]),

    Tweak(id: "proactive", name: LStr("Suggestions proactives", "Proactive suggestions"), icon: "wand.and.stars",
        group: .assistant,
        what: LStr("Les moteurs qui apprennent vos habitudes (apps ouvertes, horaires, lieux) pour suggérer apps, raccourcis et actions au bon moment : duetexpertd, proactived et les agents de connaissance Spotlight.",
                   "The engines that learn your habits (apps used, times, places) to suggest apps, shortcuts and actions at the right moment: duetexpertd, proactived and the Spotlight knowledge agents."),
        affects: [LStr("Dock (apps suggérées)", "Dock (suggested apps)"), LStr("Spotlight (Top Hits personnalisés)", "Spotlight (personalized Top Hits)"),
                  LStr("Clavier (QuickType contextuel)", "Keyboard (contextual QuickType)"), LStr("Widget Suggestions Siri", "Siri Suggestions widget"),
                  LStr("Écran verrouillé (suggestions)", "Lock screen (suggestions)")],
        breaks: LStr("Plus de suggestions d'apps dans le Dock ni Spotlight, plus de raccourcis proposés selon l'heure ou le lieu, le widget « Suggestions Siri » se vide, et QuickType perd ses propositions contextuelles. La recherche classique reste parfaitement fonctionnelle.",
                     "No more app suggestions in the Dock or Spotlight, no shortcuts offered by time or place, the “Siri Suggestions” widget empties, and QuickType loses its contextual proposals. Classic search stays fully functional."),
        reenable: LStr("L'apprentissage repart quasiment de zéro : comptez plusieurs jours d'utilisation avant que les suggestions redeviennent pertinentes.",
                       "Learning restarts almost from scratch: expect several days of use before suggestions become relevant again."),
        risk: .faible,
        mechanisms: [.agents(["com.apple.duetexpertd", "com.apple.proactived",
                              "com.apple.knowledge-agent", "com.apple.spotlightknowledged"])]),

    Tweak(id: "suggestions", name: LStr("Suggestions Spotlight & Mail", "Spotlight & Mail suggestions"), icon: "magnifyingglass.circle.fill",
        group: .assistant,
        what: LStr("suggestd analyse en local vos mails, messages et navigation pour en extraire contacts, événements et suggestions ; parsecd et parsec-fbf interrogent les serveurs Apple pour les suggestions Spotlight/Safari.",
                   "suggestd analyzes your mail, messages and browsing locally to extract contacts, events and suggestions; parsecd and parsec-fbf query Apple's servers for Spotlight/Safari suggestions."),
        affects: [LStr("Spotlight (résultats web)", "Spotlight (web results)"), LStr("Mail (détection contacts/événements)", "Mail (contact/event detection)"),
                  LStr("Safari (suggestions de recherche)", "Safari (search suggestions)"), LStr("Messages (suggestions)", "Messages (suggestions)"),
                  LStr("Calendrier (événements trouvés dans Mail)", "Calendar (events found in Mail)")],
        breaks: LStr("Spotlight n'affiche plus de résultats web ni d'actualités venant d'Apple. Mail cesse de proposer « Ajouter aux contacts » et de détecter les rendez-vous ; Calendrier perd les événements « trouvés dans Mail ». Safari n'affiche plus les suggestions Siri. La recherche locale reste intacte.",
                     "Spotlight no longer shows web results or news from Apple. Mail stops offering “Add to Contacts” and detecting appointments; Calendar loses “found in Mail” events. Safari no longer shows Siri suggestions. Local search stays intact."),
        reenable: LStr("Retour immédiat des suggestions ; la détection dans Mail reprend au fil des nouveaux messages.",
                       "Suggestions return immediately; Mail detection resumes as new messages arrive."),
        risk: .moyen,
        mechanisms: [.agents(["com.apple.suggestd", "com.apple.parsecd", "com.apple.parsec-fbf"])]),

    Tweak(id: "tips", name: LStr("Astuces (Tips)", "Tips"), icon: "lightbulb.circle.fill",
        group: .assistant,
        what: LStr("Le service de l'app « Astuces » qui envoie des notifications de conseils sur les fonctionnalités macOS, surtout après les mises à jour.",
                   "The Tips app service that sends notifications with advice about macOS features, mostly after updates."),
        affects: [LStr("App Astuces", "Tips app"), LStr("Centre de notifications", "Notification Center")],
        breaks: LStr("Plus aucune notification d'astuce Apple. L'app Astuces peut afficher un contenu obsolète. C'est tout.",
                     "No more Apple tip notifications. The Tips app may show stale content. That's all."),
        reenable: LStr("Les notifications d'astuces reprennent, notamment après la prochaine mise à jour macOS.",
                       "Tip notifications resume, especially after the next macOS update."),
        risk: .faible,
        mechanisms: [.agents(["com.apple.tipsd"])]),

    Tweak(id: "followup", name: LStr("Rappels de configuration", "Setup reminders"), icon: "checklist",
        group: .assistant,
        what: LStr("followupd génère les rappels « Terminez la configuration de votre Mac », les incitations à activer iCloud/Apple Pay et les pastilles rouges correspondantes dans Réglages Système.",
                   "followupd generates the “Finish setting up your Mac” reminders, the iCloud/Apple Pay prompts and the matching red badges in System Settings."),
        affects: [LStr("Réglages Système (pastilles rouges)", "System Settings (red badges)"), LStr("Centre de notifications", "Notification Center"),
                  LStr("Assistant de configuration", "Setup assistant")],
        breaks: LStr("Plus de rappels d'installation ni de pastilles d'incitation dans Réglages Système. Aucune fonction réelle n'est perdue, seules les relances marketing disparaissent.",
                     "No more setup reminders or prompt badges in System Settings. No real feature is lost, only the marketing nudges disappear."),
        reenable: LStr("Les rappels en attente peuvent réapparaître d'un coup dans Réglages Système.",
                       "Pending reminders may reappear all at once in System Settings."),
        risk: .faible,
        mechanisms: [.agents(["com.apple.followupd"])]),

    // ── Confidentialité & télémétrie ─────────────────────────────────────
    Tweak(id: "analytics", name: LStr("Télémétrie Apple", "Apple telemetry"), icon: "chart.bar.xaxis",
        group: .privacy,
        what: LStr("Les agents qui collectent et envoient à Apple des données d'utilisation : analytique générale, analyse de la saisie clavier, analytique de géolocalisation et daemon de confidentialité publicitaire.",
                   "The agents that collect and send usage data to Apple: general analytics, keyboard input analytics, location analytics and the ad-privacy daemon."),
        affects: [LStr("Aucune app visible", "No visible app"), LStr("Réglages > Confidentialité > Analyse et améliorations", "Settings > Privacy > Analytics & Improvements")],
        breaks: LStr("Strictement rien de visible : Apple ne reçoit plus vos statistiques d'utilisation, données de saisie agrégées et signaux de localisation anonymisés. C'est la catégorie la plus sûre à désactiver.",
                     "Nothing visible at all: Apple no longer receives your usage stats, aggregated input data and anonymized location signals. This is the safest category to disable."),
        reenable: LStr("La collecte reprend immédiatement, sans rattrapage des données non collectées.",
                       "Collection resumes immediately, with no catch-up of uncollected data."),
        risk: .faible,
        mechanisms: [.agents(["com.apple.analyticsagent", "com.apple.inputanalyticsd",
                              "com.apple.geoanalyticsd", "com.apple.ap.adprivacyd"])]),

    Tweak(id: "ads", name: LStr("Publicité personnalisée", "Personalized ads"), icon: "megaphone.fill",
        group: .privacy,
        what: LStr("Le ciblage publicitaire d'Apple, basé sur votre profil (téléchargements App Store, lectures News, localisation grossière). Correspond au réglage « Annonces personnalisées ».",
                   "Apple's ad targeting, based on your profile (App Store downloads, News reads, coarse location). Matches the “Personalized Ads” setting."),
        affects: [LStr("App Store (annonces)", "App Store (ads)"), LStr("Apple News", "Apple News"), LStr("Bourse (annonces)", "Stocks (ads)")],
        breaks: LStr("Aucune fonctionnalité perdue : vous verrez toujours des publicités dans l'App Store et News, mais génériques au lieu d'être ciblées sur votre profil.",
                     "No feature lost: you'll still see ads in the App Store and News, but generic instead of targeted to your profile."),
        reenable: LStr("La personnalisation reprend et Apple reconstitue progressivement votre profil publicitaire.",
                       "Personalization resumes and Apple gradually rebuilds your ad profile."),
        risk: .faible,
        mechanisms: [.defaultsKey(domain: "com.apple.AdLib", key: "allowApplePersonalizedAdvertising",
                                  disabledValue: .bool(false), enabledValue: .bool(true), killall: nil)]),

    Tweak(id: "diagnostics", name: LStr("Rapports de diagnostic", "Diagnostic reports"), icon: "stethoscope.circle.fill",
        group: .privacy,
        what: LStr("Les agents qui compilent et envoient les rapports de plantage à Apple, et la fenêtre « L'application a quitté de manière imprévue ».",
                   "The agents that compile and send crash reports to Apple, and the “The application quit unexpectedly” dialog."),
        affects: [LStr("Fenêtre de rapport de plantage", "Crash report dialog"), LStr("Feedback Assistant", "Feedback Assistant"),
                  LStr("Console (rapports envoyés)", "Console (sent reports)"), LStr("Support Apple", "Apple Support"),
                  LStr("Développeurs d'apps tierces", "Third-party app developers")],
        breaks: LStr("Les plantages ne déclenchent plus ni fenêtre ni envoi à Apple ; les fichiers .ips restent créés localement et lisibles dans Console. Les développeurs tiers ne reçoivent plus vos rapports de crash.",
                     "Crashes no longer trigger a dialog or a send to Apple; the .ips files are still created locally and readable in Console. Third-party developers no longer receive your crash reports."),
        reenable: LStr("Réactivation immédiate ; seuls les plantages survenus pendant la désactivation n'auront pas été transmis.",
                       "Immediate re-enable; only crashes that happened while disabled won't have been sent."),
        risk: .faible,
        mechanisms: [.agents(["com.apple.diagnostics_agent", "com.apple.DiagnosticsReporter"]),
                     .defaultsKey(domain: "com.apple.CrashReporter", key: "DialogType",
                                  disabledValue: .string("none"), enabledValue: nil, killall: nil)]),

    Tweak(id: "screentime", name: LStr("Temps d'écran", "Screen Time"), icon: "hourglass.circle.fill",
        group: .privacy,
        what: LStr("Les agents qui surveillent l'utilisation des apps et des sites pour alimenter les statistiques Temps d'écran, appliquer les limites et synchroniser le tout via iCloud.",
                   "The agents that monitor app and site usage to feed Screen Time stats, enforce limits and sync everything via iCloud."),
        affects: [LStr("Réglages > Temps d'écran", "Settings > Screen Time"), LStr("Limites d'apps", "App limits"),
                  LStr("Contrôle parental", "Parental controls"), LStr("Temps d'arrêt", "Downtime"),
                  LStr("Synchronisation iCloud des statistiques", "iCloud stats sync"), LStr("Distance de l'écran", "Screen Distance")],
        breaks: LStr("Les statistiques Temps d'écran se figent (trou définitif dans l'historique), les limites d'apps et le Temps d'arrêt ne sont plus appliqués, et si un parent supervise ce compte les restrictions ne s'appliqueront PLUS ici.",
                     "Screen Time stats freeze (a permanent gap in history), app limits and Downtime are no longer enforced, and if a parent supervises this account the restrictions will NO LONGER apply here."),
        reenable: LStr("Le suivi reprend immédiatement, mais la période désactivée reste un trou définitif. Les limites configurées se réappliquent.",
                       "Tracking resumes immediately, but the disabled period stays a permanent gap. Configured limits reapply."),
        risk: .moyen,
        mechanisms: [.agents(["com.apple.ScreenTimeAgent", "com.apple.ScreenTimeSettingsAgent",
                              "com.apple.UsageTrackingAgent"])]),

    // ── iCloud & Continuité ──────────────────────────────────────────────
    Tweak(id: "cloudphotos", name: LStr("Synchronisation Photos iCloud", "iCloud Photos sync"), icon: "icloud.circle.fill",
        group: .icloud,
        what: LStr("cloudphotod téléverse et télécharge votre photothèque iCloud en arrière-plan. Gros consommateur de réseau et de CPU après des imports.",
                   "cloudphotod uploads and downloads your iCloud photo library in the background. A heavy network and CPU user after imports."),
        affects: [LStr("Photos", "Photos"), LStr("Photos iCloud (tous vos appareils)", "iCloud Photos (all your devices)"),
                  LStr("Albums partagés", "Shared albums"), LStr("Photothèque partagée familiale", "Shared family library"),
                  LStr("Fonds d'écran utilisant vos photos", "Wallpapers using your photos")],
        breaks: LStr("DANGER silencieux : les nouvelles photos prises sur iPhone n'apparaissent plus sur le Mac et inversement, sans message d'erreur. Les albums partagés ne reçoivent plus vos ajouts. Les photos supprimées ailleurs restent visibles ici.",
                     "Silent danger: new photos taken on iPhone no longer appear on the Mac and vice versa, with no error message. Shared albums no longer receive your additions. Photos deleted elsewhere stay visible here."),
        reenable: LStr("La synchronisation reprend et rattrape tout le retard, ce qui peut prendre des heures et consommer beaucoup de bande passante. Aucune photo n'est perdue.",
                       "Sync resumes and catches up on the whole backlog, which can take hours and use a lot of bandwidth. No photo is lost."),
        risk: .eleve,
        mechanisms: [.agents(["com.apple.cloudphotod"])]),

    Tweak(id: "safarisync", name: LStr("Synchronisation Safari", "Safari sync"), icon: "safari.fill",
        group: .icloud,
        what: LStr("L'agent qui synchronise signets, liste de lecture et onglets iCloud de Safari entre vos appareils.",
                   "The agent that syncs Safari bookmarks, Reading List and iCloud Tabs across your devices."),
        affects: [LStr("Safari (signets, liste de lecture)", "Safari (bookmarks, Reading List)"), LStr("Onglets iCloud (iPhone/iPad)", "iCloud Tabs (iPhone/iPad)"),
                  LStr("Groupes d'onglets partagés", "Shared Tab Groups"), LStr("Handoff Safari", "Safari Handoff")],
        breaks: LStr("Un signet ajouté sur iPhone n'apparaît plus sur le Mac ; les groupes d'onglets partagés se désynchronisent. La navigation elle-même n'est pas affectée. Risque de doublons de signets si vous modifiez des deux côtés.",
                     "A bookmark added on iPhone no longer appears on the Mac; shared Tab Groups fall out of sync. Browsing itself is unaffected. Risk of duplicate bookmarks if you edit on both sides."),
        reenable: LStr("Resynchronisation automatique en quelques minutes ; des doublons peuvent apparaître si vous avez modifié des deux côtés pendant la coupure.",
                       "Automatic resync within minutes; duplicates may appear if you edited on both sides while it was off."),
        risk: .moyen,
        mechanisms: [.agents(["com.apple.SafariBookmarksSyncAgent"])]),

    Tweak(id: "musiccloud", name: LStr("Bibliothèque musicale iCloud", "iCloud Music Library"), icon: "music.note",
        group: .icloud,
        what: LStr("iTunesCloudd synchronise votre bibliothèque Apple Music/TV : morceaux ajoutés, playlists, « J'aime » et position de lecture.",
                   "iTunesCloudd syncs your Apple Music/TV library: added songs, playlists, likes and playback position."),
        affects: [LStr("Musique (bibliothèque, playlists)", "Music (library, playlists)"), LStr("TV (position de lecture)", "TV (playback position)"),
                  LStr("Autres appareils Apple Music", "Other Apple Music devices")],
        breaks: LStr("Les morceaux ajoutés sur iPhone n'apparaissent plus dans Musique sur le Mac, les playlists divergent, et la reprise de lecture repart du mauvais endroit. Sans effet si vous n'êtes pas abonné.",
                     "Songs added on iPhone no longer appear in Music on the Mac, playlists diverge, and resume playback starts at the wrong spot. No effect if you're not subscribed."),
        reenable: LStr("Resynchronisation automatique de la bibliothèque, généralement en quelques minutes.",
                       "Automatic library resync, usually within minutes."),
        risk: .moyen,
        mechanisms: [.agents(["com.apple.iTunesCloudd"])]),

    Tweak(id: "family", name: LStr("Partage familial", "Family Sharing"), icon: "person.3.fill",
        group: .icloud,
        what: LStr("familycircled gère le Partage familial sur ce Mac : achats partagés, demandes d'achat des enfants, localisation des membres et Temps d'écran familial.",
                   "familycircled manages Family Sharing on this Mac: shared purchases, kids' purchase requests, member location and family Screen Time."),
        affects: [LStr("App Store (achats partagés)", "App Store (shared purchases)"), LStr("Demandes d'achat (enfants)", "Purchase requests (kids)"),
                  LStr("Localiser (membres de la famille)", "Find My (family members)"), LStr("Abonnements partagés", "Shared subscriptions"),
                  LStr("Temps d'écran familial", "Family Screen Time")],
        breaks: LStr("Sur ce Mac uniquement : les apps achetées par la famille peuvent refuser de se télécharger, les demandes d'achat des enfants n'arrivent plus, la position des membres disparaît de Localiser. Les autres appareils ne sont pas affectés.",
                     "On this Mac only: family-purchased apps may refuse to download, kids' purchase requests no longer arrive, member location disappears from Find My. Other devices are unaffected."),
        reenable: LStr("Reconnexion automatique au groupe familial, généralement immédiate.",
                       "Automatic reconnection to the family group, usually instant."),
        risk: .moyen,
        mechanisms: [.agents(["com.apple.familycircled"])]),

    Tweak(id: "wallet", name: LStr("Wallet & Apple Pay", "Wallet & Apple Pay"), icon: "creditcard.fill",
        group: .icloud,
        what: LStr("passd gère vos cartes Wallet (bancaires, fidélité, billets) et l'autorisation des transactions Apple Pay sur le Mac.",
                   "passd manages your Wallet cards (bank, loyalty, tickets) and authorization of Apple Pay transactions on the Mac."),
        affects: [LStr("Apple Pay (Safari et apps)", "Apple Pay (Safari and apps)"), LStr("Wallet (cartes, billets)", "Wallet (cards, tickets)"),
                  LStr("Touch ID pour les paiements", "Touch ID for payments"), LStr("Confirmation d'achat iPhone à proximité", "Nearby iPhone purchase confirmation")],
        breaks: LStr("Le bouton Apple Pay dans Safari et les apps ne répond plus ; les paiements échouent au moment de confirmer avec Touch ID. Vos cartes restent intactes sur iPhone/Apple Watch, seul ce Mac est concerné.",
                     "The Apple Pay button in Safari and apps stops responding; payments fail when confirming with Touch ID. Your cards stay intact on iPhone/Apple Watch, only this Mac is affected."),
        reenable: LStr("Les cartes se revalident automatiquement ; certaines banques redemandent une vérification avant de réautoriser Apple Pay sur ce Mac.",
                       "Cards revalidate automatically; some banks ask for verification again before re-authorizing Apple Pay on this Mac."),
        risk: .eleve,
        mechanisms: [.agents(["com.apple.passd"])]),

    Tweak(id: "sidecar", name: LStr("Sidecar & AirPlay", "Sidecar & AirPlay"), icon: "rectangle.on.rectangle",
        group: .icloud,
        what: LStr("Le relais Sidecar (iPad comme second écran) et l'agent d'interface AirPlay (diffusion vers Apple TV, HomePod et téléviseurs compatibles).",
                   "The Sidecar relay (iPad as a second display) and the AirPlay UI agent (streaming to Apple TV, HomePod and compatible TVs)."),
        affects: [LStr("Sidecar (iPad comme écran)", "Sidecar (iPad as display)"), LStr("Recopie d'écran AirPlay", "AirPlay screen mirroring"),
                  LStr("Diffusion audio vers HomePod", "Audio streaming to HomePod"), LStr("Réglages > Écrans (option iPad)", "Settings > Displays (iPad option)")],
        breaks: LStr("L'iPad n'apparaît plus dans Réglages > Écrans ni dans le menu de recopie. Le menu AirPlay devient incomplet : impossible d'étendre l'écran vers une Apple TV ou d'envoyer l'audio vers un HomePod depuis la barre des menus.",
                     "The iPad no longer appears in Settings > Displays or the mirroring menu. The AirPlay menu becomes incomplete: you can't extend the display to an Apple TV or send audio to a HomePod from the menu bar."),
        reenable: LStr("Retour immédiat de Sidecar et du menu AirPlay dès la session suivante.",
                       "Sidecar and the AirPlay menu return immediately in the next session."),
        risk: .moyen,
        mechanisms: [.agents(["com.apple.sidecar-relay", "com.apple.AirPlayUIAgent"])]),

    Tweak(id: "icloudsave", name: LStr("iCloud par défaut à l'enregistrement", "iCloud as default save location"), icon: "externaldrive.fill.badge.icloud",
        group: .icloud,
        what: LStr("Par défaut, les fenêtres « Enregistrer » proposent iCloud Drive comme destination. Ce réglage remet un dossier local du Mac par défaut.",
                   "By default, Save dialogs offer iCloud Drive as the destination. This setting makes a local Mac folder the default instead."),
        affects: [LStr("TextEdit", "TextEdit"), LStr("Pages/Numbers/Keynote", "Pages/Numbers/Keynote"),
                  LStr("Aperçu", "Preview"), LStr("Toute app à documents", "Any document-based app")],
        breaks: LStr("Rien ne casse : les nouvelles fenêtres d'enregistrement proposeront un dossier local au lieu d'iCloud Drive. Vous pouvez toujours choisir iCloud manuellement.",
                     "Nothing breaks: new Save dialogs will offer a local folder instead of iCloud Drive. You can still choose iCloud manually."),
        reenable: LStr("Les fenêtres d'enregistrement reproposent iCloud Drive par défaut, au prochain lancement de chaque app.",
                       "Save dialogs offer iCloud Drive again by default, at each app's next launch."),
        risk: .faible,
        mechanisms: [.defaultsKey(domain: "NSGlobalDomain", key: "NSDocumentSaveNewDocumentsToCloud",
                                  disabledValue: .bool(false), enabledValue: nil, killall: nil)]),

    // ── Médias & apps intégrées ──────────────────────────────────────────
    Tweak(id: "photoanalyse", name: LStr("Analyse Photos & Médias", "Photos & Media analysis"), icon: "photo.circle.fill",
        group: .media,
        what: LStr("photoanalysisd et mediaanalysisd analysent photos et vidéos en arrière-plan : reconnaissance de visages, objets, scènes, texte (Live Text). Gros consommateurs de CPU après un import.",
                   "photoanalysisd and mediaanalysisd analyze photos and videos in the background: face, object, scene and text recognition (Live Text). Heavy CPU users after an import."),
        affects: [LStr("Photos (recherche, onglet Personnes)", "Photos (search, People tab)"), LStr("Souvenirs & diaporamas", "Memories & slideshows"),
                  LStr("Live Text (texte dans les images)", "Live Text (text in images)"), LStr("Recherche visuelle", "Visual Look Up"),
                  LStr("Autocollants depuis des photos", "Stickers from photos")],
        breaks: LStr("Dans Photos : l'onglet Personnes n'intègre plus les nouveaux visages, la recherche par contenu ignore les nouvelles photos, plus aucun Souvenir généré. Live Text et la recherche visuelle échouent sur les nouvelles images. Ce qui est déjà analysé reste recherchable.",
                     "In Photos: the People tab stops adding new faces, content search ignores new photos, no new Memories are generated. Live Text and Visual Look Up fail on new images. Already-analyzed content stays searchable."),
        reenable: LStr("L'analyse reprend et traite tout l'arriéré : le Mac peut chauffer et le ventilateur tourner plusieurs heures (de préférence sur secteur, la nuit).",
                       "Analysis resumes and processes the whole backlog: the Mac may heat up and the fan run for several hours (ideally on power, overnight)."),
        risk: .moyen,
        mechanisms: [.agents(["com.apple.photoanalysisd", "com.apple.mediaanalysisd"])]),

    Tweak(id: "widgets", name: LStr("Météo, News & Bourse", "Weather, News & Stocks"), icon: "cloud.sun.circle.fill",
        group: .media,
        what: LStr("Les daemons de données des apps Météo, News et Bourse. Ils se réveillent régulièrement pour rafraîchir prévisions, articles et cours, même si vous n'ouvrez jamais ces apps.",
                   "The data daemons of the Weather, News and Stocks apps. They wake regularly to refresh forecasts, articles and quotes, even if you never open these apps."),
        affects: [LStr("App Météo + widgets", "Weather app + widgets"), LStr("App News + widgets", "News app + widgets"),
                  LStr("App Bourse + widgets", "Stocks app + widgets"), LStr("Centre de notifications", "Notification Center"),
                  LStr("Écran verrouillé (complications)", "Lock screen (complications)"), LStr("Alertes météo", "Weather alerts")],
        breaks: LStr("Les widgets Météo/News/Bourse affichent des données figées ou « -- ». Les alertes météo n'arrivent plus. Les trois apps s'ouvrent mais peuvent rester vides. Siri ne sait plus répondre « quel temps fera-t-il demain ? ».",
                     "The Weather/News/Stocks widgets show frozen data or “--”. Weather alerts stop arriving. The three apps open but may stay empty. Siri can no longer answer “what's the weather tomorrow?”."),
        reenable: LStr("Les données se rafraîchissent dans la minute qui suit la réactivation.",
                       "Data refreshes within a minute of re-enabling."),
        risk: .moyen,
        mechanisms: [.agents(["com.apple.weatherd", "com.apple.newsd", "com.apple.financed"])]),

    Tweak(id: "gamecenter", name: LStr("Game Center", "Game Center"), icon: "gamecontroller.fill",
        group: .media,
        what: LStr("Le daemon Game Center : profil joueur, classements, succès, invitations et matchmaking multijoueur.",
                   "The Game Center daemon: player profile, leaderboards, achievements, invitations and multiplayer matchmaking."),
        affects: [LStr("Jeux App Store & Apple Arcade", "App Store & Apple Arcade games"), LStr("Classements & succès", "Leaderboards & achievements"),
                  LStr("Multijoueur Game Center", "Game Center multiplayer"), LStr("Réglages > Game Center", "Settings > Game Center")],
        breaks: LStr("À l'ouverture d'un jeu, la connexion Game Center échoue ou tourne en boucle ; quelques jeux refusent la sauvegarde en ligne. Pas de classements, de succès ni de multijoueur. Sans conséquence si vous ne jouez pas.",
                     "When a game opens, the Game Center sign-in fails or loops; a few games refuse online saves. No leaderboards, achievements or multiplayer. No impact if you don't play."),
        reenable: LStr("Reconnexion automatique au profil joueur ; les succès débloqués hors ligne se resynchronisent.",
                       "Automatic reconnection to the player profile; achievements earned offline resync."),
        risk: .faible,
        mechanisms: [.agents(["com.apple.gamed"])]),

    Tweak(id: "music", name: LStr("Agents Musique & TV", "Music & TV agents"), icon: "music.note.list",
        group: .media,
        what: LStr("Trois agents d'arrière-plan des apps Musique/TV : téléchargement des pochettes, gestion de la bibliothèque et détection des appareils en mode synchronisation.",
                   "Three background agents for the Music/TV apps: artwork download, library management and detection of devices in sync mode."),
        affects: [LStr("Musique (pochettes, bibliothèque)", "Music (artwork, library)"), LStr("TV", "TV"),
                  LStr("Finder (synchronisation iPhone/iPad par câble)", "Finder (wired iPhone/iPad sync)"), LStr("Podcasts (partiellement)", "Podcasts (partly)")],
        breaks: LStr("Pochettes manquantes ou grises, bibliothèque mise à jour seulement quand Musique est ouvert, et surtout : l'iPhone/iPad branché en USB peut ne PLUS apparaître dans la barre latérale du Finder. Rebranchez après réactivation si besoin.",
                     "Missing or gray artwork, library updated only when Music is open, and above all: an iPhone/iPad plugged in over USB may NO LONGER appear in the Finder sidebar. Reconnect after re-enabling if needed."),
        reenable: LStr("Les pochettes se retéléchargent et la détection d'appareils revient immédiatement.",
                       "Artwork re-downloads and device detection returns immediately."),
        risk: .moyen,
        mechanisms: [.agents(["com.apple.AMPArtworkAgent", "com.apple.AMPLibraryAgent",
                              "com.apple.AMPDeviceDiscoveryAgent"])]),

    Tweak(id: "memoji", name: LStr("Memoji (avatars)", "Memoji (avatars)"), icon: "face.smiling.fill",
        group: .media,
        what: LStr("avatarsd gère la création, le rendu et la synchronisation iCloud de vos Memoji.",
                   "avatarsd handles creation, rendering and iCloud sync of your Memoji."),
        affects: [LStr("Messages (autocollants Memoji)", "Messages (Memoji stickers)"), LStr("Fiche de contact (avatar)", "Contact card (avatar)"),
                  LStr("Clavier d'autocollants", "Sticker keyboard")],
        breaks: LStr("Les autocollants Memoji ne se chargent plus dans Messages, votre avatar de contact peut s'afficher en silhouette grise, et la création de Memoji échoue. Aucune perte : tout est conservé dans iCloud.",
                     "Memoji stickers no longer load in Messages, your contact avatar may show as a gray silhouette, and Memoji creation fails. No loss: everything stays in iCloud."),
        reenable: LStr("Les Memoji se rechargent depuis iCloud en quelques instants.",
                       "Memoji reload from iCloud within moments."),
        risk: .faible,
        mechanisms: [.agents(["com.apple.avatarsd"])]),

    Tweak(id: "homekit", name: LStr("HomeKit (Maison)", "HomeKit (Home)"), icon: "house.fill",
        group: .media,
        what: LStr("homed est le daemon de l'app Maison : état des accessoires, exécution des scènes, notifications domotiques et rôle de relais résidentiel éventuel.",
                   "homed is the Home app daemon: accessory state, scene execution, home-automation notifications and possible home-hub relay role."),
        affects: [LStr("App Maison", "Home app"), LStr("Siri (« allume la lumière »)", "Siri (“turn on the light”)"),
                  LStr("Notifications caméras/capteurs/sonnettes", "Camera/sensor/doorbell notifications"), LStr("Automatisations si ce Mac sert de hub", "Automations if this Mac is a hub"),
                  LStr("Centre de contrôle (module Maison)", "Control Center (Home module)")],
        breaks: LStr("L'app Maison ne charge plus vos accessoires sur ce Mac, Siri ne pilote plus la domotique d'ici, et les notifications de caméras ou de capteurs n'arrivent plus. Vos accessoires et l'app Maison sur iPhone continuent normalement.",
                     "The Home app no longer loads your accessories on this Mac, Siri no longer controls home automation from here, and camera/sensor notifications stop arriving. Your accessories and the Home app on iPhone keep working normally."),
        reenable: LStr("L'app Maison se resynchronise depuis iCloud, généralement en moins d'une minute.",
                       "The Home app resyncs from iCloud, usually in under a minute."),
        risk: .eleve,
        mechanisms: [.agents(["com.apple.homed"])]),

    Tweak(id: "callhistory", name: LStr("Historique d'appels iPhone", "iPhone call history"), icon: "phone.fill",
        group: .media,
        what: LStr("Deux assistants qui synchronisent l'historique des appels de votre iPhone vers le Mac, pour FaceTime et les appels relayés.",
                   "Two helpers that sync your iPhone's call history to the Mac, for FaceTime and relayed calls."),
        affects: [LStr("FaceTime (onglet récents)", "FaceTime (recents tab)"), LStr("Rappel en un clic depuis le Mac", "One-click call back from the Mac"),
                  LStr("Notifications d'appels manqués synchronisées", "Synced missed-call notifications")],
        breaks: LStr("L'onglet « Récents » de FaceTime ne reflète plus les appels de l'iPhone, et rappeler depuis l'historique devient impossible. Recevoir/passer des appels relayés continue en général de fonctionner.",
                     "FaceTime's Recents tab no longer reflects iPhone calls, and calling back from history becomes impossible. Receiving/making relayed calls generally keeps working."),
        reenable: LStr("L'historique se resynchronise depuis l'iPhone à la prochaine connexion.",
                       "History resyncs from the iPhone at the next connection."),
        risk: .faible,
        mechanisms: [.agents(["com.apple.CallHistoryPluginHelper", "com.apple.CallHistorySyncHelper"])]),

    Tweak(id: "imagecapture", name: LStr("Ouverture auto de Photos", "Auto-open Photos"), icon: "camera.fill",
        group: .media,
        what: LStr("Quand vous branchez un iPhone, un appareil photo ou une carte SD, macOS ouvre automatiquement Photos (ou l'app configurée).",
                   "When you plug in an iPhone, camera or SD card, macOS automatically opens Photos (or the configured app)."),
        affects: [LStr("Photos (ouverture au branchement)", "Photos (open on connect)"), LStr("Transfert d'images", "Image Capture")],
        breaks: LStr("Rien ne casse : Photos ne s'ouvrira simplement plus tout seul au branchement d'un appareil. L'import manuel reste possible à tout moment.",
                     "Nothing breaks: Photos simply won't open by itself when you plug in a device. Manual import is still possible anytime."),
        reenable: LStr("Photos se rouvrira automatiquement au prochain branchement d'un appareil.",
                       "Photos will auto-open again the next time you connect a device."),
        risk: .faible,
        mechanisms: [.defaultsKey(domain: "com.apple.ImageCapture", key: "disableHotPlug",
                                  disabledValue: .bool(true), enabledValue: nil, killall: nil)]),

    Tweak(id: "tmreminder", name: LStr("Rappels Time Machine", "Time Machine reminders"), icon: "clock.arrow.circlepath",
        group: .media,
        what: LStr("TMHelperAgent affiche « Voulez-vous utiliser ce disque pour Time Machine ? » au branchement d'un disque et les notifications de sauvegardes en retard.",
                   "TMHelperAgent shows “Do you want to use this disk with Time Machine?” when a disk is plugged in, and late-backup notifications."),
        affects: [LStr("Notifications Time Machine", "Time Machine notifications"), LStr("Popup au branchement d'un disque", "Popup on disk connect")],
        breaks: LStr("Plus de proposition automatique à chaque disque branché et plus de rappel si les sauvegardes sont en retard. Les sauvegardes configurées continuent normalement, seuls les rappels disparaissent.",
                     "No more automatic prompt when a disk is plugged in and no reminder if backups are late. Configured backups keep running normally, only the reminders disappear."),
        reenable: LStr("Les rappels et propositions reviennent immédiatement.",
                       "Reminders and prompts return immediately."),
        risk: .faible,
        mechanisms: [.agents(["com.apple.TMHelperAgent"])]),

    // ── Interface & confort ──────────────────────────────────────────────
    Tweak(id: "animations", name: LStr("Animations de fenêtres", "Window animations"), icon: "wand.and.rays",
        group: .ui,
        what: LStr("Les animations d'ouverture/fermeture des fenêtres et le temps d'animation du redimensionnement des boîtes de dialogue (0,2 s par défaut, réduit à 0,001 s). L'interface paraît plus réactive.",
                   "Window open/close animations and the dialog resize animation time (0.2 s by default, cut to 0.001 s). The interface feels noticeably snappier."),
        affects: [LStr("Toutes les apps (fenêtres, dialogues)", "All apps (windows, dialogs)"), LStr("Fenêtres d'enregistrement", "Save dialogs"),
                  LStr("Pas Mission Control ni les Espaces", "Not Mission Control or Spaces")],
        breaks: LStr("Rien de fonctionnel : les fenêtres apparaissent instantanément au lieu de s'animer. Ne touche ni à Mission Control, ni au Dock, ni aux transitions d'Espaces. Effet au prochain lancement de chaque app.",
                     "Nothing functional: windows appear instantly instead of animating. Doesn't affect Mission Control, the Dock or Spaces transitions. Takes effect at each app's next launch."),
        reenable: LStr("Les clés de réglage sont supprimées et les animations d'origine reviennent au prochain lancement des apps.",
                       "The settings keys are removed and the original animations return at the apps' next launch."),
        risk: .faible,
        mechanisms: [.defaultsKey(domain: "NSGlobalDomain", key: "NSAutomaticWindowAnimationsEnabled",
                                  disabledValue: .bool(false), enabledValue: nil, killall: nil),
                     .defaultsKey(domain: "NSGlobalDomain", key: "NSWindowResizeTime",
                                  disabledValue: .float(0.001), enabledValue: nil, killall: nil)]),

    Tweak(id: "dockbounce", name: LStr("Rebond des icônes du Dock", "Dock icon bouncing"), icon: "dock.rectangle",
        group: .ui,
        what: LStr("L'animation de rebond des icônes du Dock quand une app en arrière-plan demande votre attention (message reçu, tâche terminée, erreur).",
                   "The bouncing animation of Dock icons when a background app wants your attention (message received, task done, error)."),
        affects: [LStr("Dock", "Dock"), LStr("Alertes des apps en arrière-plan", "Background app alerts")],
        breaks: LStr("Les apps qui réclament votre attention ne rebondissent plus ; vous pourriez rater une alerte (un installeur qui attend une confirmation). Le badge rouge reste visible. Le Dock redémarre (bref clignotement).",
                     "Apps wanting your attention no longer bounce; you might miss an alert (an installer waiting for confirmation). The red badge stays visible. The Dock restarts (a brief flicker)."),
        reenable: LStr("Le rebond revient dès la réactivation (le Dock redémarre à nouveau brièvement).",
                       "Bouncing returns as soon as you re-enable it (the Dock restarts briefly again)."),
        risk: .faible,
        mechanisms: [.defaultsKey(domain: "com.apple.dock", key: "no-bouncing",
                                  disabledValue: .bool(true), enabledValue: nil, killall: "Dock")]),

    Tweak(id: "autocorrect", name: LStr("Corrections automatiques du texte", "Automatic text corrections"), icon: "textformat.abc",
        group: .ui,
        what: LStr("Trois automatismes de saisie système : correction orthographique automatique, majuscule automatique en début de phrase, et point inséré par double espace.",
                   "Three system-wide typing automations: automatic spelling correction, automatic capitalization at the start of a sentence, and a period inserted by double space."),
        affects: [LStr("Notes", "Notes"), LStr("Mail", "Mail"), LStr("Messages", "Messages"),
                  LStr("Safari (formulaires)", "Safari (forms)"), LStr("Toute zone de texte native", "Any native text field"),
                  LStr("Pas les apps avec réglage propre (Word, VS Code…)", "Not apps with their own setting (Word, VS Code…)")],
        breaks: LStr("Votre texte n'est plus corrigé ni capitalisé automatiquement : idéal pour taper du code ou du texte multilingue, gênant si vous comptiez sur la correction. Le soulignement rouge de vérification reste actif. Effet au prochain lancement des apps.",
                     "Your text is no longer auto-corrected or capitalized: great for typing code or multilingual text, annoying if you relied on correction. The red spell-check underline stays active. Takes effect at the apps' next launch."),
        reenable: LStr("Les trois automatismes reviennent au prochain lancement de chaque app.",
                       "The three automations return at each app's next launch."),
        risk: .faible,
        mechanisms: [.defaultsKey(domain: "NSGlobalDomain", key: "NSAutomaticSpellingCorrectionEnabled",
                                  disabledValue: .bool(false), enabledValue: nil, killall: nil),
                     .defaultsKey(domain: "NSGlobalDomain", key: "NSAutomaticCapitalizationEnabled",
                                  disabledValue: .bool(false), enabledValue: nil, killall: nil),
                     .defaultsKey(domain: "NSGlobalDomain", key: "NSAutomaticPeriodSubstitutionEnabled",
                                  disabledValue: .bool(false), enabledValue: nil, killall: nil)]),

    Tweak(id: "dsstore", name: LStr("Fichiers .DS_Store externes", "External .DS_Store files"), icon: "doc.badge.gearshape",
        group: .ui,
        what: LStr("Le Finder sème des fichiers cachés .DS_Store sur chaque dossier visité, y compris les partages réseau et clés USB, ce qui pollue les NAS, dépôts Git et clés échangées avec des PC Windows.",
                   "The Finder scatters hidden .DS_Store files in every folder it visits, including network shares and USB drives, cluttering NAS, Git repos and drives shared with Windows PCs."),
        affects: [LStr("Finder (volumes réseau et USB uniquement)", "Finder (network and USB volumes only)"), LStr("NAS / partages SMB", "NAS / SMB shares"),
                  LStr("Clés USB partagées avec Windows", "USB drives shared with Windows")],
        breaks: LStr("Sur les volumes réseau et USB uniquement : la disposition des icônes n'est plus mémorisée (le Finder revient à l'affichage par défaut). Les volumes internes ne changent pas. Les .DS_Store existants ne sont pas supprimés, utilisez l'onglet Nettoyage.",
                     "On network and USB volumes only: icon layout is no longer remembered (the Finder reverts to the default view). Internal volumes don't change. Existing .DS_Store files aren't removed, use the Cleanup tab."),
        reenable: LStr("Le Finder recommence à mémoriser (et à semer des .DS_Store) sur les volumes externes.",
                       "The Finder starts remembering (and scattering .DS_Store) on external volumes again."),
        risk: .faible,
        mechanisms: [.defaultsKey(domain: "com.apple.desktopservices", key: "DSDontWriteNetworkStores",
                                  disabledValue: .bool(true), enabledValue: nil, killall: nil),
                     .defaultsKey(domain: "com.apple.desktopservices", key: "DSDontWriteUSBStores",
                                  disabledValue: .bool(true), enabledValue: nil, killall: nil)]),

    Tweak(id: "appnap", name: LStr("App Nap", "App Nap"), icon: "zzz",
        group: .ui,
        what: LStr("App Nap ralentit fortement les apps invisibles en arrière-plan pour économiser l'énergie. Ce réglage le désactive globalement.",
                   "App Nap heavily slows invisible background apps to save energy. This setting disables it globally."),
        affects: [LStr("Toutes les apps en arrière-plan", "All background apps"), LStr("Autonomie de la batterie", "Battery life"),
                  LStr("Apps de rendu/serveurs locaux/téléchargements", "Render/local-server/download apps")],
        breaks: LStr("Attention au sens : ici on désactive une économie d'énergie. Conséquence : autonomie réduite sur MacBook et un peu plus de chauffe, car les apps en arrière-plan restent à pleine vitesse. Utile si un rendu ou serveur local se fait brider.",
                     "Note the direction: here you disable an energy saver. Result: shorter battery life on a MacBook and a little more heat, since background apps stay at full speed. Useful if a render or local server gets throttled."),
        reenable: LStr("App Nap se réactive et les apps en arrière-plan sont de nouveau ralenties (comportement normal de macOS).",
                       "App Nap re-enables and background apps are throttled again (normal macOS behavior)."),
        risk: .faible,
        mechanisms: [.defaultsKey(domain: "NSGlobalDomain", key: "NSAppSleepDisabled",
                                  disabledValue: .bool(true), enabledValue: nil, killall: nil)]),

    // ── Système (admin) ──────────────────────────────────────────────────
    Tweak(id: "spotlightindex", name: LStr("Indexation Spotlight", "Spotlight indexing"), icon: "magnifyingglass",
        group: .system,
        what: LStr("L'indexation continue de tous les volumes par Spotlight (mds et mdworker), qui peut consommer beaucoup de CPU et d'E/S disque, surtout après une mise à jour ou de gros transferts.",
                   "Spotlight's continuous indexing of all volumes (mds and mdworker), which can use a lot of CPU and disk I/O, especially after an update or large transfers."),
        affects: [LStr("Spotlight (⌘Espace)", "Spotlight (⌘Space)"), LStr("Recherche du Finder", "Finder search"),
                  LStr("Recherche dans Mail", "Mail search"), LStr("Launchpad (recherche)", "Launchpad (search)"),
                  LStr("Siri (recherche de fichiers)", "Siri (file search)"), LStr("Apps utilisant CoreSpotlight", "Apps using CoreSpotlight")],
        breaks: LStr("La recherche ne trouve PLUS vos fichiers : Spotlight ne renvoie quasiment rien, la recherche du Finder et de Mail deviennent inutilisables, et les apps qui s'appuient sur l'index sont dégradées. À réserver aux cas où mds consomme durablement trop.",
                     "Search NO LONGER finds your files: Spotlight returns almost nothing, Finder and Mail search become unusable, and apps relying on the index are degraded. Reserve for cases where mds uses too many resources for a long time."),
        reenable: LStr("macOS réindexe TOUT depuis zéro : plusieurs heures de CPU et de disque, recherche incomplète pendant ce temps. Prévoyez de le faire sur secteur.",
                       "macOS reindexes EVERYTHING from scratch: several hours of CPU and disk, incomplete search during that time. Plan to do it on power."),
        risk: .eleve,
        mechanisms: [.admin(label: "mdutil : indexation de tous les volumes",
                            disableCmd: "mdutil -a -i off", enableCmd: "mdutil -a -i on",
                            checkCmd: "mdutil -s /", disabledMarker: "disabled")]),

    Tweak(id: "powernap", name: LStr("Power Nap", "Power Nap"), icon: "bolt.fill",
        group: .system,
        what: LStr("Power Nap réveille périodiquement le Mac en veille pour relever les mails, synchroniser iCloud, mettre à jour Localiser et lancer les sauvegardes Time Machine.",
                   "Power Nap periodically wakes the sleeping Mac to fetch mail, sync iCloud, update Find My and run Time Machine backups."),
        affects: [LStr("Mail (relève en veille)", "Mail (fetch during sleep)"), LStr("Time Machine (sauvegardes en veille)", "Time Machine (sleep backups)"),
                  LStr("Localiser (position à jour)", "Find My (updated location)"), LStr("iCloud (sync en veille)", "iCloud (sleep sync)"),
                  LStr("Batterie en veille", "Battery during sleep")],
        breaks: LStr("En veille, le Mac devient réellement inerte : pas de relève de mails, pas de sauvegarde Time Machine nocturne, position dans Localiser figée. Tout reprend au réveil. Gain : batterie mieux préservée en veille prolongée.",
                     "During sleep the Mac becomes truly idle: no mail fetch, no overnight Time Machine backup, frozen Find My location. Everything resumes on wake. Benefit: better preserved battery during long sleep."),
        reenable: LStr("Le comportement d'origine revient dès la prochaine mise en veille.",
                       "The original behavior returns at the next sleep."),
        risk: .faible,
        mechanisms: [.admin(label: "pmset : powernap (tous modes d'alimentation)",
                            disableCmd: "pmset -a powernap 0", enableCmd: "pmset -a powernap 1",
                            checkCmd: "pmset -g | awk '/powernap/ {print $2}'", disabledMarker: "0")]),

    Tweak(id: "bootchime", name: LStr("Son de démarrage", "Startup chime"), icon: "speaker.slash.fill",
        group: .system,
        what: LStr("Le carillon joué au démarrage du Mac, contrôlé par la variable NVRAM StartupMute.",
                   "The chime played when the Mac starts, controlled by the StartupMute NVRAM variable."),
        affects: [LStr("Haut-parleurs au démarrage uniquement", "Speakers at startup only")],
        breaks: LStr("Rien : le Mac démarre simplement en silence. Vous perdez seulement l'indication sonore que le démarrage a commencé.",
                     "Nothing: the Mac simply starts silently. You only lose the audible cue that startup has begun."),
        reenable: LStr("Le carillon revient au prochain démarrage.",
                       "The chime returns at the next startup."),
        risk: .faible,
        mechanisms: [.admin(label: "nvram : StartupMute",
                            disableCmd: "nvram StartupMute=%01", enableCmd: "nvram StartupMute=%00",
                            checkCmd: "nvram StartupMute 2>/dev/null", disabledMarker: "%01")]),
]
